services:
  - type: web
    name: blood-link-backend
    env: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 7d
    autoDeploy: false
